name: Dart CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Flutter action
      uses: subosito/flutter-action@v1.3.2
      with:
    # The Flutter version to make available on the path
        flutter-version: 1.17.2
    # The Flutter build release channel
        channel: stable
